// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt-IhX5rUyZgrYnpsiRxOP09lfP86HFhQ',
    appId: '1:739935747973:web:a1e3a30b3819d808858eec',
    messagingSenderId: '739935747973',
    projectId: 'salebeer-4fe2d',
    authDomain: 'salebeer-4fe2d.firebaseapp.com',
    storageBucket: 'salebeer-4fe2d.firebasestorage.app',
    measurementId: 'G-CKSMRG6WE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqlQVSEHi_RO9-1woRrL0e1giGBySFdVI',
    appId: '1:739935747973:android:784c04d5d0e9f488858eec',
    messagingSenderId: '739935747973',
    projectId: 'salebeer-4fe2d',
    storageBucket: 'salebeer-4fe2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlbkizb91GDAA9nn2mIt98JgKFvLbSdhY',
    appId: '1:739935747973:ios:50dad31b153423ca858eec',
    messagingSenderId: '739935747973',
    projectId: 'salebeer-4fe2d',
    storageBucket: 'salebeer-4fe2d.firebasestorage.app',
    iosBundleId: 'com.example.beerSale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlbkizb91GDAA9nn2mIt98JgKFvLbSdhY',
    appId: '1:739935747973:ios:50dad31b153423ca858eec',
    messagingSenderId: '739935747973',
    projectId: 'salebeer-4fe2d',
    storageBucket: 'salebeer-4fe2d.firebasestorage.app',
    iosBundleId: 'com.example.beerSale',
  );
}
